@startuml

node [Room service] as sroom
node [Speaker service] as sspeaker
node [Talk service] as stalk
node [Voting service] as svoting
node [Schedule Service] as sschedule
node [Front-end] as frontend

frontend ..> sroom
[frontend] ..> sspeaker
[frontend] ..> stalk
[frontend] ..> sschedule
[frontend] ..> svoting

@enduml
