FROM nginx

MAINTAINER agoncal

LABEL name="Conference Web"
LABEL description="Angular front-end for the conference application"
LABEL url="http://localhost:80"
LABEL vendor="@agoncal"

EXPOSE 80

COPY ./dist /usr/share/nginx/html
