/**
 * Schedule
 * Allows rating for a talk and gives all the details about the ratings
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional } from '@angular/core';
import { Http, Headers, URLSearchParams } from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType } from '@angular/http';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class RatingApi {
    protected basePath = 'http://localhost:8082/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    public links: { [key: string]: string; } = {};

    public getResponse(body: any): any {
        if (!body.data)
            return body;

        if (body.links) {
            this.links = {};
            for (let key in body.links) {
                this.links[key] = body.links[key] !== undefined ? body.links[key] : null;
            }
        }
        return body.data;
    }

    constructor(protected http: Http, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }

        this.basePath += '/conference-rating/api';

    }

    /**
     * Finds all the ratings
     * 
     * @param page 
     */
    public allRatings(page?: number, extraHttpRequestParams?: any): Observable<Array<models.Rating>> {
        return this.allRatingsWithHttpInfo(page, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the ratings for an attendee
     * 
     * @param attendeeId 
     */
    public allRatingsByAttendee(attendeeId: string, extraHttpRequestParams?: any): Observable<Array<models.Rating>> {
        return this.allRatingsByAttendeeWithHttpInfo(attendeeId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the ratings for a session
     * 
     * @param sessionId 
     */
    public allRatingsBySession(sessionId: string, extraHttpRequestParams?: any): Observable<Array<models.Rating>> {
        return this.allRatingsBySessionWithHttpInfo(sessionId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Allows an attendee to rate a talk
     * 
     * @param sessionId 
     * @param mark 
     */
    public rate(sessionId: string, mark?: number, extraHttpRequestParams?: any): Observable<{}> {
        return this.rateWithHttpInfo(sessionId, mark, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }


    /**
     * Finds all the ratings
     * 
     * @param page 
     */
    public allRatingsWithHttpInfo(page?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/ratings`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (page !== undefined) {
            if (<any>page instanceof Date) {
                queryParameters.set('page', (<any>page).d.toISOString());
            } else {
                queryParameters.set('page', <any>page);
            }
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the ratings for an attendee
     * 
     * @param attendeeId 
     */
    public allRatingsByAttendeeWithHttpInfo(attendeeId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/ratings/attendees/${attendeeId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'attendeeId' is not null or undefined
        if (attendeeId === null || attendeeId === undefined) {
            throw new Error('Required parameter attendeeId was null or undefined when calling allRatingsByAttendee.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the ratings for a session
     * 
     * @param sessionId 
     */
    public allRatingsBySessionWithHttpInfo(sessionId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/ratings/sessions/${sessionId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'sessionId' is not null or undefined
        if (sessionId === null || sessionId === undefined) {
            throw new Error('Required parameter sessionId was null or undefined when calling allRatingsBySession.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Allows an attendee to rate a talk
     * 
     * @param sessionId 
     * @param mark 
     */
    public rateWithHttpInfo(sessionId: string, mark?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/ratings/${sessionId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        let formParams = new URLSearchParams();

        // verify required parameter 'sessionId' is not null or undefined
        if (sessionId === null || sessionId === undefined) {
            throw new Error('Required parameter sessionId was null or undefined when calling rate.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        headers.set('Content-Type', 'application/x-www-form-urlencoded');

        if (mark !== undefined) {
            formParams.set('mark', <any>mark);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
