/**
 * Schedule
 * Gives all the details of the schedule
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional } from '@angular/core';
import { Http, Headers, URLSearchParams } from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType } from '@angular/http';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class ScheduleApi {
    protected basePath = 'http://localhost:8083/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();


    public links: { [key: string]: string; } = {};

    public getResponse(body: any): any {
        if (!body.data)
            return body;

        if (body.links) {
            this.links = {};
            for (let key in body.links) {
                this.links[key] = body.links[key] !== undefined ? body.links[key] : null;
            }
        }
        return body.data;
    }
    constructor(protected http: Http, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }

        this.basePath += '/conference-schedule/api';

    }

    /**
     * Adds a new session to the conference
     * 
     * @param body Session to be created
     */
    public add(body: models.Session, extraHttpRequestParams?: any): Observable<{}> {
        return this.addWithHttpInfo(body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions
     * 
     * @param page 
     */
    public allSessions(page?: number, extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsWithHttpInfo(page, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Friday
     * 
     */
    public allSessionsFriday(extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsFridayWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Friday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsFridayByRoom(roomId: string, extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsFridayByRoomWithHttpInfo(roomId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Monday
     * 
     */
    public allSessionsMonday(extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsMondayWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Monday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsMondayByRoom(roomId: string, extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsMondayByRoomWithHttpInfo(roomId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Thursday
     * 
     */
    public allSessionsThursday(extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsThursdayWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Thursday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsThursdayByRoom(roomId: string, extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsThursdayByRoomWithHttpInfo(roomId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Tuesday
     * 
     */
    public allSessionsTuesday(extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsTuesdayWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Tuesday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsTuesdayByRoom(roomId: string, extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsTuesdayByRoomWithHttpInfo(roomId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Wednesday
     * 
     */
    public allSessionsWednesday(extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsWednesdayWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds all the sessions for Wednesday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsWednesdayByRoom(roomId: string, extraHttpRequestParams?: any): Observable<Array<models.Session>> {
        return this.allSessionsWednesdayByRoomWithHttpInfo(roomId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Deletes a session
     * 
     * @param id 
     */
    public remove(id: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.removeWithHttpInfo(id, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }

    /**
     * Finds a session by ID
     * 
     * @param id 
     */
    public retrieve(id: string, extraHttpRequestParams?: any): Observable<models.Session> {
        return this.retrieveWithHttpInfo(id, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return this.getResponse(response.json());
                }
            });
    }


    /**
     * Adds a new session to the conference
     * 
     * @param body Session to be created
     */
    public addWithHttpInfo(body: models.Session, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling add.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions
     * 
     * @param page 
     */
    public allSessionsWithHttpInfo(page?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (page !== undefined) {
            if (<any>page instanceof Date) {
                queryParameters.set('page', (<any>page).d.toISOString());
            } else {
                queryParameters.set('page', <any>page);
            }
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Friday
     * 
     */
    public allSessionsFridayWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/friday`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Friday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsFridayByRoomWithHttpInfo(roomId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/friday/${roomId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'roomId' is not null or undefined
        if (roomId === null || roomId === undefined) {
            throw new Error('Required parameter roomId was null or undefined when calling allSessionsFridayByRoom.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Monday
     * 
     */
    public allSessionsMondayWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/monday`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Monday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsMondayByRoomWithHttpInfo(roomId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/monday/${roomId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'roomId' is not null or undefined
        if (roomId === null || roomId === undefined) {
            throw new Error('Required parameter roomId was null or undefined when calling allSessionsMondayByRoom.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Thursday
     * 
     */
    public allSessionsThursdayWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/thursday`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Thursday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsThursdayByRoomWithHttpInfo(roomId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/thursday/${roomId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'roomId' is not null or undefined
        if (roomId === null || roomId === undefined) {
            throw new Error('Required parameter roomId was null or undefined when calling allSessionsThursdayByRoom.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Tuesday
     * 
     */
    public allSessionsTuesdayWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/tuesday`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Tuesday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsTuesdayByRoomWithHttpInfo(roomId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/tuesday/${roomId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'roomId' is not null or undefined
        if (roomId === null || roomId === undefined) {
            throw new Error('Required parameter roomId was null or undefined when calling allSessionsTuesdayByRoom.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Wednesday
     * 
     */
    public allSessionsWednesdayWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/wednesday`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds all the sessions for Wednesday on a specific room
     * 
     * @param roomId 
     */
    public allSessionsWednesdayByRoomWithHttpInfo(roomId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/wednesday/${roomId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'roomId' is not null or undefined
        if (roomId === null || roomId === undefined) {
            throw new Error('Required parameter roomId was null or undefined when calling allSessionsWednesdayByRoom.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Deletes a session
     * 
     * @param id 
     */
    public removeWithHttpInfo(id: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/${id}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling remove.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Finds a session by ID
     * 
     * @param id 
     */
    public retrieveWithHttpInfo(id: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/sessions/${id}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling retrieve.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
