/**
 * Schedule
 * Allows rating for a talk and gives all the details about the ratings
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Rating {
    links?: { [key: string]: string; };

    id?: string;

    sessionId?: string;

    attendeeId?: string;

    mark?: number;

}
